// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.selected = function() {
    return this.click(function(event) {
      var className, clickTarget;
      if ($(event.target).is(this)) {
        clickTarget = event.target;
      } else {
        clickTarget = $(event.target).closest(this)[0];
      }
      if (clickTarget === event.currentTarget) {
        clickTarget = $(clickTarget);
        className = clickTarget.attr("class").split(" ")[0];
        $("*[class*=" + className + "]").not(clickTarget).removeClass("selected odd even");
        clickTarget.addClass("selected");
        if (clickTarget.hasClass("odd")) {
          clickTarget.addClass("even");
          return clickTarget.removeClass("odd");
        } else {
          clickTarget.addClass("odd");
          return clickTarget.removeClass("even");
        }
      }
    });
  };

}).call(this);
